# Importing Libraries

In [1]:
import numpy as np
import pandas as pd 

In [2]:
import tensorflow as tf
import keras
from keras import datasets

In [3]:
datasets

<module 'keras.api.datasets' from 'C:\\Users\\Rudra\\AppData\\Roaming\\Python\\Python311\\site-packages\\keras\\api\\datasets\\__init__.py'>

In [4]:
(x_train , y_train) , (x_test , y_test) = datasets.mnist.load_data()

In [5]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
x_train.shape


(60000, 28, 28)

In [8]:
x_test.shape


(10000, 28, 28)

In [9]:
#Transforming the images into the acceptable size by neural networks
width, height = 28,28
input_size = (width,height ,1)

In [10]:
input_size

(28, 28, 1)

In [11]:
x_train = x_train.reshape(x_train.shape[0], height,width, 1)
x_test = x_test.reshape(x_test.shape[0], height,width, 1)

In [12]:
x_train.shape , x_test.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

In [13]:
y_train.shape , y_test.shape

((60000,), (10000,))

In [14]:
# val represents to validation data 
# first we validate the data and then we use the final testing data 

from sklearn.model_selection import train_test_split
x_train ,x_val , y_train , y_val = train_test_split(x_train,y_train, test_size=0.1,)

###### basically validation is  Used to tune the model's hyperparameters and to provide an unbiased evaluation of a model fit on the training dataset while tuning model hyperparameters.

In [16]:
x_val.shape

(6000, 28, 28, 1)

In [17]:
x_train = (x_train -  x_train.mean())/ x_train.std()
x_val = (x_val - x_val.mean())/ x_val.std()
x_test = (x_test - x_test.mean())/ x_test.std()

In [18]:
x_train

array([[[[-0.42428927],
         [-0.42428927],
         [-0.42428927],
         ...,
         [-0.42428927],
         [-0.42428927],
         [-0.42428927]],

        [[-0.42428927],
         [-0.42428927],
         [-0.42428927],
         ...,
         [-0.42428927],
         [-0.42428927],
         [-0.42428927]],

        [[-0.42428927],
         [-0.42428927],
         [-0.42428927],
         ...,
         [-0.42428927],
         [-0.42428927],
         [-0.42428927]],

        ...,

        [[-0.42428927],
         [-0.42428927],
         [-0.42428927],
         ...,
         [-0.42428927],
         [-0.42428927],
         [-0.42428927]],

        [[-0.42428927],
         [-0.42428927],
         [-0.42428927],
         ...,
         [-0.42428927],
         [-0.42428927],
         [-0.42428927]],

        [[-0.42428927],
         [-0.42428927],
         [-0.42428927],
         ...,
         [-0.42428927],
         [-0.42428927],
         [-0.42428927]]],


       [[[-0.42428927],


##### Categorizing the Y(Labels) training , testing  and validation data

In [19]:
y_train

array([1, 7, 1, ..., 0, 9, 9], dtype=uint8)

In [20]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [21]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
y_test = keras.utils.to_categorical(y_test)
y_val = keras.utils.to_categorical(y_val)

# Model Buliding

In [25]:
from keras.models import Sequential
from keras.layers import Dropout , Dense , Flatten , Input , Conv2D ,MaxPooling2D ,AveragePooling2D

In [31]:
model = Sequential()

model.add(Conv2D(6, kernel_size=(5, 5), strides=(1, 1), activation='tanh', input_shape=(28, 28, 1)))
model.add(AveragePooling2D(pool_size=(2, 2), strides=(1, 1)))
model.add(Conv2D(16, kernel_size=(5, 5), strides=(1, 1), activation='tanh'))
model.add(AveragePooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(120, kernel_size=(5, 5), strides=(1, 1), activation='tanh'))

model.add(Flatten())
model.add(Dense(84, activation='tanh'))
model.add(Dense(num_labels, activation='softmax'))

C:\Users\Rudra\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 24, 24, 6)      │           156 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 23, 23, 6)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 19, 19, 16)     │         2,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 9, 9, 16)       │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 5, 5, 120)      │        48,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 3000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 84)             │       252,084 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           850 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics =['accuracy'])

In [37]:
history = model.fit(x_train, y_train,batch_size=32, epochs = 20, verbose =1 , validation_data=(x_val,y_val))

Epoch 1/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.9037 - loss: 0.3173 - val_accuracy: 0.9570 - val_loss: 0.1366
Epoch 2/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.9720 - loss: 0.0925 - val_accuracy: 0.9672 - val_loss: 0.1075
Epoch 3/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9772 - loss: 0.0735 - val_accuracy: 0.9727 - val_loss: 0.0852
Epoch 4/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9788 - loss: 0.0694 - val_accuracy: 0.9798 - val_loss: 0.0656
Epoch 5/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.9814 - loss: 0.0593 - val_accuracy: 0.9763 - val_loss: 0.0710
Epoch 6/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9814 - loss: 0.0587 - val_accuracy: 0.9760 - val_loss: 0.0858
Epoch 7/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9847 - loss: 0.0539 - val_accuracy: 0.9808 - val_loss: 0.0628
Epoch 8/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9837 - loss: 0

In [40]:
score = model.evaluate(x_test,y_test , verbose =1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9817 - loss: 0.0528


In [41]:
score

[0.04208749532699585, 0.9861999750137329]